"use client";

const industrySectors = {
  Utilities: 6,
  Healthcare: 5,
  Telecommunications: 4,
  "Consumer Goods": 3,
  Technology: 3,
  Manufacturing: 3,
  Finance: 2,
  Retail: 2,
  Agriculture: 2,
  Transportation: 2,
  "Real Estate": 1,
  Energy: 1,
};

const regions = {
  "Northern America": 6,
  "Northern Europe": 6,
  Oceania: 5,
  "Western Europe": 4,
  "Southern Europe": 4,
  "East Asia": 5,
  "South-East Asia": 3,
  "South Asia": 3,
  "Central Asia": 3,
  "Eastern Europe": 3,
  "North Africa": 3,
  "Southern Africa": 3,
  "South America": 3,
  "Middle East": 3,
  "Central America": 2,
  "East Africa": 2,
  "West Africa": 2,
};

const creditRatings = [
  "Aaa",
  "Aa1",
  "Aa2",
  "Aa3",
  "A1",
  "A2",
  "A3",
  "Baa1",
  "Baa2",
  "Baa3",
  "Ba1",
  "Ba2",
  "Ba3",
  "B1",
  "B2",
  "B3",
  "Caa1",
  "Caa2",
  "Caa3",
  "Ca",
  "C",
];
const financialExplanations = {
  loanAmount:
    "The loan amount is the total sum borrowed by the borrower. A higher loan amount typically increases the lender's risk, which can result in a higher interest rate.",
  collateralValue:
    "The collateral value is the worth of the asset pledged by the borrower. A higher collateral value reduces the lender's risk, potentially leading to a lower interest rate.",
  debtToIncomeRatio:
    "The debt-to-income ratio measures the borrower's debt payments compared to their income. A higher ratio indicates higher risk for the lender and can lead to a higher interest rate.",
  loanToValueRatio:
    "The loan-to-value ratio compares the loan amount to the value of the collateral. A higher ratio suggests greater risk for the lender, which may result in a higher interest rate.",
  region:
    "The region where the borrower is located can affect the interest rate due to local economic conditions, market demand, and regulatory environment.",
  sector:
    "The sector indicates the industry in which the borrower operates. Different sectors have varying levels of risk associated with them, influencing the interest rate.",
  subordination:
    "Subordination refers to the order of repayment in case of default. Loans with higher subordination are riskier, potentially leading to higher interest rates.",
  loanTerm:
    "The loan term is the length of time over which the loan is scheduled to be repaid. A shorter loan term can lead to higher interest costs"
};



const profitSplitExplanations = {
  hq_revenue:
    "The total revenue generated by the headquarters. Higher revenue often indicates greater economic importance within the group.",
  hq_cost:
    "The total costs incurred by the headquarters. Lower costs relative to revenue may indicate higher profitability.",
  hq_assets:
    "The total assets held by the headquarters. More assets often signify greater capital involvement.",
  hq_liabilities:
    "The total liabilities held by the headquarters. High liabilities relative to assets may reduce the financial stability of the headquarters.",
  subs_revenue:
    "The total revenue generated by the subsidiary. A higher revenue may increase the subsidiary's economic importance.",
  subs_cost:
    "The total costs incurred by the subsidiary. Lower costs relative to revenue may indicate higher profitability for the subsidiary.",
  subs_assets:
    "The total assets held by the subsidiary. More assets often signify greater capital involvement.",
  subs_liabilities:
    "The total liabilities held by the subsidiary. High liabilities relative to assets may reduce the financial stability of the subsidiary.",
  industry:
    "The industry in which the entity operates. Different industries have varying economic importance and profit potential.",
  function:
    "The function performed by the entity (e.g., R&D, marketing). Certain functions are considered more value-adding, impacting profit allocation.",
};

const industriesProfitSplit = [
  "manufacturing",
  "services",
  "technology",
  "retail",
  "finance",
  "healthcare",
  "energy",
  "transportation",
];

const functionsProfitSplit = [
  "manufacturing",
  "R&D",
  "marketing",
  "sales",
  "administration",
  "logistics",
  "holding",
];

const disclaimerInterestRate= "The interest rate prediction was generated using a machine learning model trained on sample data. This model aims to provide an arm's length price comparable to market standards, but the results may not represent a 100% reliable arm's length price.";
const disclaimerProfitSplit = "The profit split prediction was generated using a machine learning model trained on sample data. This model aims to provide an arm's length profit allocation comparable to market standards, but the results may not represent a 100% reliable arm's length allocation.";


export {
  industrySectors,
  regions,
  creditRatings,
  financialExplanations,
  profitSplitExplanations,
  industriesProfitSplit,
  functionsProfitSplit,
  disclaimerInterestRate,
  disclaimerProfitSplit
};
